version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/nest-db?schema=public
      - JWT_SECRET_KEY=secret
      - JWT_EXPIRATION_TIME=8h
      - PORT=4000
    restart: unless-stopped
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/
      - API_URL=http://backend:4000/
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nest-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
